-- AUTOINCREMENT for INTEGER PRIMARY KEY
CREATE TABLE t1 (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
INSERT INTO t1 VALUES (NULL, 'alice');
INSERT INTO t1 VALUES (NULL, 'bob');
INSERT INTO t1 VALUES (NULL, 'carol');
SELECT * FROM t1;

-- Explicit ID then auto
INSERT INTO t1 VALUES (10, 'dave');
INSERT INTO t1 VALUES (NULL, 'eve');
SELECT * FROM t1;

-- INTEGER PRIMARY KEY without AUTOINCREMENT (still auto-assigns)
CREATE TABLE t2 (id INTEGER PRIMARY KEY, val TEXT);
INSERT INTO t2 VALUES (NULL, 'x');
INSERT INTO t2 VALUES (NULL, 'y');
INSERT INTO t2 VALUES (5, 'z');
INSERT INTO t2 VALUES (NULL, 'w');
SELECT * FROM t2;
