-- NULLS FIRST / NULLS LAST in ORDER BY
CREATE TABLE t (id INTEGER, v TEXT);
INSERT INTO t VALUES (1, 'banana');
INSERT INTO t VALUES (2, NULL);
INSERT INTO t VALUES (3, 'apple');
INSERT INTO t VALUES (4, NULL);
INSERT INTO t VALUES (5, 'cherry');

-- NULLS LAST (put NULLs at end)
SELECT id, v FROM t ORDER BY v NULLS LAST, id;

-- NULLS FIRST (put NULLs at start, default)
SELECT id, v FROM t ORDER BY v NULLS FIRST, id;

-- NULLS LAST with DESC
SELECT id, v FROM t ORDER BY v DESC NULLS LAST, id;
