-- IS NULL / IS NOT NULL
SELECT 1 IS NULL;
SELECT NULL IS NULL;
SELECT 1 IS NOT NULL;
SELECT NULL IS NOT NULL;
SELECT '' IS NULL;
SELECT 0 IS NULL;
CREATE TABLE t (id INTEGER, v TEXT);
INSERT INTO t VALUES (1, 'a');
INSERT INTO t VALUES (2, NULL);
INSERT INTO t VALUES (3, 'b');
SELECT id FROM t WHERE v IS NULL;
SELECT id FROM t WHERE v IS NOT NULL ORDER BY id;
