-- FIRST_VALUE and LAST_VALUE window functions
CREATE TABLE t (id INTEGER, dept TEXT, val INTEGER);
INSERT INTO t VALUES (1, 'A', 100);
INSERT INTO t VALUES (2, 'A', 200);
INSERT INTO t VALUES (3, 'A', 300);
INSERT INTO t VALUES (4, 'B', 50);
INSERT INTO t VALUES (5, 'B', 150);

-- FIRST_VALUE with PARTITION BY
SELECT id, dept, val, FIRST_VALUE(val) OVER (PARTITION BY dept ORDER BY val) AS first_v FROM t ORDER BY id;
