-- Type coercion and TYPEOF
SELECT TYPEOF(1);
SELECT TYPEOF('hello');
SELECT TYPEOF(NULL);
SELECT TYPEOF(1 + 2);

-- Arithmetic with text numbers
SELECT '5' + 3;
SELECT '10' * 2;
SELECT '3' - 1;

-- CAST
SELECT CAST('123' AS INTEGER);
SELECT CAST(456 AS TEXT);
SELECT CAST(NULL AS INTEGER);
SELECT CAST(NULL AS TEXT);
