-- UNION with ORDER BY and LIMIT tests
CREATE TABLE t1 (id INTEGER PRIMARY KEY, val TEXT);
CREATE TABLE t2 (id INTEGER PRIMARY KEY, val TEXT);
INSERT INTO t1 VALUES (1, 'apple');
INSERT INTO t1 VALUES (2, 'banana');
INSERT INTO t1 VALUES (3, 'cherry');
INSERT INTO t2 VALUES (1, 'banana');
INSERT INTO t2 VALUES (2, 'date');
INSERT INTO t2 VALUES (3, 'elderberry');

-- UNION removes duplicates
SELECT val FROM t1 UNION SELECT val FROM t2 ORDER BY val;

-- UNION ALL keeps duplicates
SELECT val FROM t1 UNION ALL SELECT val FROM t2 ORDER BY val;

-- INTERSECT
SELECT val FROM t1 INTERSECT SELECT val FROM t2;

-- EXCEPT
SELECT val FROM t1 EXCEPT SELECT val FROM t2 ORDER BY val;
