-- UNION with LIMIT comma syntax
CREATE TABLE t1 (id INTEGER, val TEXT);
INSERT INTO t1 VALUES (1, 'a');
INSERT INTO t1 VALUES (2, 'b');
INSERT INTO t1 VALUES (3, 'c');

CREATE TABLE t2 (id INTEGER, val TEXT);
INSERT INTO t2 VALUES (4, 'd');
INSERT INTO t2 VALUES (5, 'e');
INSERT INTO t2 VALUES (6, 'f');

-- UNION ALL with LIMIT offset, count
SELECT * FROM t1 UNION ALL SELECT * FROM t2 ORDER BY id LIMIT 1, 3;

-- UNION ALL with regular LIMIT OFFSET
SELECT * FROM t1 UNION ALL SELECT * FROM t2 ORDER BY id LIMIT 3 OFFSET 1;
