CREATE TABLE t1 (id INTEGER, name TEXT);
INSERT INTO t1 VALUES (1, 'alice');
INSERT INTO t1 VALUES (2, 'bob');
CREATE TABLE t2 (id INTEGER, name TEXT);
INSERT INTO t2 VALUES (3, 'charlie');
INSERT INTO t2 VALUES (1, 'alice');
SELECT id, name FROM t1 UNION ALL SELECT id, name FROM t2;
