CREATE TABLE t1 (id INTEGER, name TEXT);
INSERT INTO t1 VALUES (1, 'alice');
INSERT INTO t1 VALUES (2, NULL);
CREATE TABLE t2 (id INTEGER, name TEXT);
INSERT INTO t2 VALUES (2, NULL);
INSERT INTO t2 VALUES (3, 'charlie');
SELECT id, name FROM t1 UNION SELECT id, name FROM t2;
