CREATE TABLE t1 (id INTEGER, val TEXT);
INSERT INTO t1 VALUES (1, 'a');
INSERT INTO t1 VALUES (2, NULL);
INSERT INTO t1 VALUES (3, 'c');

CREATE TABLE t2 (id INTEGER, val TEXT);
INSERT INTO t2 VALUES (2, NULL);
INSERT INTO t2 VALUES (3, 'c');
INSERT INTO t2 VALUES (4, 'd');

SELECT id, val FROM t1 INTERSECT SELECT id, val FROM t2;

SELECT id, val FROM t1 EXCEPT SELECT id, val FROM t2;
