CREATE TABLE nums (id INTEGER, val INTEGER);
INSERT INTO nums VALUES (1, 10);
INSERT INTO nums VALUES (2, 20);
INSERT INTO nums VALUES (3, 30);
INSERT INTO nums VALUES (4, 40);
INSERT INTO nums VALUES (5, 50);

SELECT * FROM nums WHERE val BETWEEN 20 AND 40;

SELECT id FROM nums WHERE id BETWEEN 2 AND 4;
