CREATE TABLE t (id INTEGER, val INTEGER);
INSERT INTO t VALUES (1, 10);
INSERT INTO t VALUES (2, -5);
INSERT INTO t VALUES (3, 20);

SELECT -val FROM t;

SELECT * FROM t WHERE val = -5;

SELECT id, val, -val FROM t;
