CREATE TABLE t1 (id INTEGER, name TEXT, val INTEGER);
INSERT INTO t1 VALUES (1, 'Hello', -5);
INSERT INTO t1 VALUES (2, 'World', 42);
INSERT INTO t1 VALUES (3, NULL, 0);

-- ABS
SELECT ABS(val) FROM t1;
SELECT ABS(-10);

-- LENGTH
SELECT LENGTH(name) FROM t1;
SELECT LENGTH(12345);

-- UPPER / LOWER
SELECT UPPER(name) FROM t1;
SELECT LOWER(name) FROM t1;

-- TYPEOF
SELECT TYPEOF(id), TYPEOF(name), TYPEOF(val) FROM t1;
SELECT TYPEOF(NULL);

-- TRIM
SELECT TRIM('  hello  ');
SELECT TRIM(name) FROM t1;
