CREATE TABLE t1 (id INTEGER, a INTEGER, b TEXT);
INSERT INTO t1 VALUES (1, NULL, 'x');
INSERT INTO t1 VALUES (2, 10, NULL);
INSERT INTO t1 VALUES (3, NULL, NULL);
INSERT INTO t1 VALUES (4, 5, 'y');

-- COALESCE
SELECT COALESCE(a, 0) FROM t1;
SELECT COALESCE(a, b, 'default') FROM t1;
SELECT COALESCE(NULL, NULL, 42);

-- NULLIF
SELECT NULLIF(1, 1);
SELECT NULLIF(1, 2);
SELECT NULLIF(a, 5) FROM t1;

-- MAX/MIN scalar functions
SELECT MAX(1, 5, 3);
SELECT MIN(10, 2, 8);
