CREATE TABLE t1 (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO t1 VALUES (1, 'alice');
INSERT INTO t1 VALUES (2, 'bob');

-- INSERT OR IGNORE: skip conflicting row
INSERT OR IGNORE INTO t1 VALUES (1, 'carol');
INSERT OR IGNORE INTO t1 VALUES (3, 'dave');
SELECT * FROM t1 ORDER BY id;

-- INSERT OR REPLACE: replace conflicting row
INSERT OR REPLACE INTO t1 VALUES (2, 'eve');
INSERT OR REPLACE INTO t1 VALUES (4, 'frank');
SELECT * FROM t1 ORDER BY id;
