CREATE TABLE t1 (id INTEGER, dept TEXT, val INTEGER);
INSERT INTO t1 VALUES (1, 'eng', 10);
INSERT INTO t1 VALUES (2, 'eng', 20);
INSERT INTO t1 VALUES (3, 'sales', 10);
INSERT INTO t1 VALUES (4, 'sales', 20);
INSERT INTO t1 VALUES (5, 'eng', 10);

-- COUNT(DISTINCT col) - unique departments
SELECT COUNT(DISTINCT dept) FROM t1;

-- COUNT(DISTINCT col) - unique values
SELECT COUNT(DISTINCT val) FROM t1;

-- COUNT(DISTINCT) with GROUP BY
SELECT dept, COUNT(DISTINCT val) FROM t1 GROUP BY dept;

-- COUNT(DISTINCT) with NULL
INSERT INTO t1 VALUES (6, NULL, 10);
SELECT COUNT(DISTINCT dept) FROM t1;

-- Regular COUNT vs DISTINCT COUNT
SELECT COUNT(dept), COUNT(DISTINCT dept) FROM t1;
