CREATE TABLE t1 (id INTEGER, name TEXT, val INTEGER);
INSERT INTO t1 VALUES (1, 'alice', 10);
INSERT INTO t1 VALUES (2, 'bob', 20);
INSERT INTO t1 VALUES (3, 'carol', 30);
INSERT INTO t1 VALUES (4, 'dave', 40);
INSERT INTO t1 VALUES (5, 'eve', 50);

-- LIMIT only
SELECT * FROM t1 ORDER BY id LIMIT 3;

-- LIMIT with OFFSET
SELECT * FROM t1 ORDER BY id LIMIT 2 OFFSET 2;

-- LIMIT with WHERE
SELECT * FROM t1 WHERE val > 15 ORDER BY id LIMIT 2;

-- LIMIT with ORDER BY DESC
SELECT * FROM t1 ORDER BY val DESC LIMIT 3;

-- LIMIT 0 (empty result)
SELECT * FROM t1 LIMIT 0;

-- OFFSET only (large offset)
SELECT * FROM t1 ORDER BY id LIMIT 10 OFFSET 3;
