CREATE TABLE t1 (id INTEGER, name TEXT, val INTEGER);
INSERT INTO t1 VALUES (1, 'alice', -10);
INSERT INTO t1 VALUES (2, 'bob', 30);
INSERT INTO t1 VALUES (3, 'carol', -20);
INSERT INTO t1 VALUES (4, 'dave', 5);

-- ORDER BY ABS(val)
SELECT * FROM t1 ORDER BY ABS(val);

-- ORDER BY ABS(val) DESC
SELECT * FROM t1 ORDER BY ABS(val) DESC;

-- ORDER BY UPPER(name)
SELECT * FROM t1 ORDER BY UPPER(name);

-- ORDER BY val + 100
SELECT * FROM t1 ORDER BY val + 100;

-- ORDER BY LENGTH(name)
SELECT * FROM t1 ORDER BY LENGTH(name), id;
