-- Aggregate DISTINCT tests (SUM, AVG, GROUP_CONCAT)
CREATE TABLE t1 (category TEXT, val INTEGER);
INSERT INTO t1 VALUES ('a', 10);
INSERT INTO t1 VALUES ('a', 10);
INSERT INTO t1 VALUES ('a', 20);
INSERT INTO t1 VALUES ('b', 30);
INSERT INTO t1 VALUES ('b', 30);

-- SUM(DISTINCT val)
SELECT SUM(DISTINCT val) FROM t1;

-- AVG(DISTINCT val)
SELECT AVG(DISTINCT val) FROM t1;

-- GROUP_CONCAT(DISTINCT category)
SELECT GROUP_CONCAT(DISTINCT category) FROM t1;
