-- DEFAULT values in CREATE TABLE
CREATE TABLE t1 (id INTEGER PRIMARY KEY, name TEXT DEFAULT 'unknown', status INTEGER DEFAULT 0);
INSERT INTO t1(id) VALUES (1);
INSERT INTO t1(id, name) VALUES (2, 'alice');
INSERT INTO t1 VALUES (3, 'bob', 1);
SELECT * FROM t1 ORDER BY id;
