-- LEFT OUTER JOIN and RIGHT OUTER JOIN syntax
CREATE TABLE t1 (id INTEGER, name TEXT);
CREATE TABLE t2 (id INTEGER, val TEXT);
INSERT INTO t1 VALUES (1, 'alice');
INSERT INTO t1 VALUES (2, 'bob');
INSERT INTO t1 VALUES (3, 'carol');
INSERT INTO t2 VALUES (1, 'x');
INSERT INTO t2 VALUES (2, 'y');
INSERT INTO t2 VALUES (4, 'z');

-- LEFT OUTER JOIN (same as LEFT JOIN)
SELECT t1.name, t2.val FROM t1 LEFT OUTER JOIN t2 ON t1.id = t2.id ORDER BY t1.name;

-- RIGHT OUTER JOIN (same as RIGHT JOIN)
SELECT t1.name, t2.val FROM t1 RIGHT OUTER JOIN t2 ON t1.id = t2.id ORDER BY t2.id;
